// src/app/layout.tsx
import { ReduxProvider } from "@/provider/redux-provider";
import '@/styles/globals.css';
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <main>{children}</main>
          <Toaster position="top-center" reverseOrder={false} />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
